name: ETL Workflow Group 18

on:
#  schedule:
#    - cron: '0 */3 * * *' # Run every 3 hours
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup R environment
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'
      
      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('**/lockfile') }}
          restore-keys: ${{ runner.os }}-r-
      
      - name: Install packages
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          Rscript -e 'install.packages(c("ggplot2","dplyr","readr","RSQLite","DBI","lubridate","tidyr", "knitr"))'
      
      - name: Execute R script for Initial table creation and validation
        run: |
          Rscript R/data_workflow.R
      
      - name: Execute R script for automation analysis
        run: |
          Rscript R/Analysis.R
      
      - name: Add files
        run: |
          git config --global user.email "akarsha.shrivastava@warwick.ac.uk"
          git config --global user.name "AkarshaShrivastava19"
      
      - name: Check if ecomdata.db has changed
        id: check-db
        run: |
          git diff --exit-code --name-only | grep 'ecomdata.db' && echo "::set-output name=changed::true" || echo "::set-output name=changed::false"
      
      - name: Commit and push if ecomdata.db has changed
        if: steps.check-db.outputs.changed == 'true'
        run: |
          git add ecomdata.db
          git commit -m "Update ecomdata.db"
          git push
      
      - name: Push changes
        if: steps.check-db.outputs.changed == 'true'
        uses: ad-m/github-push-action@v0.6.0
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: main
