name: ETL Workflow Group 18

on:
#  schedule:
#    - cron: '0 */3 * * *' # Run every 3 hours
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup R environment
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'
      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('**/lockfile') }}
          restore-keys: |
            ${{ runner.os }}-r-
      - name: Install packages
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          Rscript -e 'install.packages(c("ggplot2","dplyr","readr","RSQLite","DBI"))'
      - name: Execute R script
        run: |
          Rscript R/load_data.R

      - name: Check for changes
        id: git-check
        run: |
          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes to commit."
            echo "::set-output name=changes::false"
          else
            echo "Changes detected."
            echo "::set-output name=changes::true"
          fi
          
      - name: Add files
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git config --global user.email "akarsha.shrivastava@warwick.ac.uk"
          git config --global user.name "Akarsha"
          git add ecomdata.db
          
      - name: Commit files
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git commit -m "Update database"
      - name: Push changes
        if: steps.git-check.outputs.changes == 'true'
        uses: ad-m/github-push-action@v0.6.0
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: main

      
